---
_package:
  - { state: "latest", name: "python3" }
  - { state: "latest", name: "bash" }
  - { state: "latest", name: "bash-completion" }

# _service:
#   - { enabled: "yes", state: "present",  name: "" }

_install_script:
  - { url: "https://get.rke2.io", checksum: "", dest: "/tmp/install.sh"  }

# _pkill_script:
#   - { url: "", checksum: "", dest: ""  }

# _uninstall_script:
#   - { url: "", checksum: "", dest: ""  }
